import img1 from "@/public/mobile/apple/Blue/pic1.webp";
import img2 from "@/public/mobile/samsung/gold/pic1.webp";

export const products = [
  {
    category: "mobile",
    brandName: "Apple",
    productName: "iphone 15 pro max",
    color: "Blue Titanium",
    storage: "256GB",
    img: img1,
    starRating: 4.5,
    rating: 23,
    reviews: 34,
    highlights: [
      "256 GB ROM",
      "17.02 cm (6.7 inch) Super Retina XDR Display",
      "48MP + 12MP + 12MP | 12MP Front Camera",
      "A17 Pro Chip 6 Core Processor",
    ],
    salePrice: 139999,
    launchPrice: 149999,
  },
  {
    category: "Mobile",
    brandName: "Samsung",
    productName: "Galaxy S24 Ultra 5G",
    color: "Titanium Black",
    storage: "256GB",
    img: img2,
    starRating: 4.7,
    rating: 32,
    reviews: 50,
    highlights: [
      "12 GB RAM | 256 GB ROM",
      "17.27 cm (6.8 inch) Quad HD+ Display",
      "200MP + 10MP + 12MP + 10MP | 12MP Front Camera",
      "5000 mAh Lithium Ion Battery",
      "Qualcomm Snapdragon 8 Gen 2 Processor",
    ],
    salePrice: 129999,
    launchPrice: 139999,
  },
  {
    category: "Mobile",
    brandName: "Samsung",
    productName: "Galaxy S24 Ultra 5G",
    color: "Titanium Black",
    storage: "256GB",
    img: img2,
    starRating: 4.7,
    rating: 32,
    reviews: 50,
    highlights: [
      "12 GB RAM | 256 GB ROM",
      "17.27 cm (6.8 inch) Quad HD+ Display",
      "200MP + 10MP + 12MP + 10MP | 12MP Front Camera",
      "5000 mAh Lithium Ion Battery",
      "Qualcomm Snapdragon 8 Gen 2 Processor",
    ],
    salePrice: 129999,
    launchPrice: 139999,
  },
  {
    category: "Mobile",
    brandName: "Samsung",
    productName: "Galaxy S24 Ultra 5G",
    color: "Titanium Black",
    storage: "256GB",
    varients: [
      {
        color: "Titanium Black",
        storage: "256 GB",
        inStock: 10,
      },
      {
        color: "Titanium Black",
        storage: "512 GB",
        inStock: 10,
      },
      {
        color: "Titanium Black",
        storage: "1 TB",
        inStock: 10,
      },
      {
        color: "Titanium Gold",
        storage: "256 GB",
        inStock: 10,
      },
      {
        color: "Titanium Gold",
        storage: "512 GB",
        inStock: 10,
      },
      {
        color: "Titanium Gold",
        storage: "1 TB",
        inStock: 10,
      },
      {
        color: "Titanium Voilet",
        storage: "256 GB",
        inStock: 10,
      },
      {
        color: "Titanium Voilet",
        storage: "512 GB",
        inStock: 10,
      },
      {
        color: "Titanium Voilet",
        storage: "1 TB",
        inStock: 10,
      },
    ],
    img: img2,
    starRating: 4.7,
    rating: 32,
    reviews: 50,
    highlights: [
      "12 GB RAM | 256 GB ROM",
      "17.27 cm (6.8 inch) Quad HD+ Display",
      "200MP + 10MP + 12MP + 10MP | 12MP Front Camera",
      "5000 mAh Lithium Ion Battery",
      "Qualcomm Snapdragon 8 Gen 2 Processor",
    ],
    salePrice: 129999,
    launchPrice: 139999,
  },
];
